# Generated by Django 5.0.6 on 2024-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Saaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saaco_name", models.CharField(max_length=20)),
                ("saaco_email", models.EmailField(max_length=254)),
                ("saaco_phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
