# Generated by Django 5.0.6 on 2024-07-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wezeshaMobileApp",
            "0002_remove_farmer_id_farmer_cooperative_farmer_farmer_id_and_more",
        ),
        (
            "wezeshaWebPortalCooperative",
            "0002_remove_cooperative_id_cooperative_cooperative_id",
        ),
        ("wezeshaWebPortalSaaco", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saaco",
            name="cooperative_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saaco_cooperative",
                to="wezeshaWebPortalCooperative.cooperative",
            ),
        ),
        migrations.AddField(
            model_name="saaco",
            name="farmer_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saaco_farmers",
                to="wezeshaMobileApp.farmer",
            ),
        ),
        migrations.AddField(
            model_name="saaco",
            name="saaco_password",
            field=models.CharField(default="defaultpassword", max_length=13),
        ),
    ]
