# Generated by Django 5.0.6 on 2024-07-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farmer_first_name", models.CharField(max_length=20)),
                ("farmer_last_name", models.CharField(max_length=20)),
                ("farmer_email", models.EmailField(max_length=254)),
                ("farmer_phone_number", models.CharField(max_length=20)),
                ("farmer_loan_status", models.CharField(max_length=20)),
            ],
        ),
    ]
