# Generated by Django 5.0.6 on 2024-07-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wezeshaMobileApp", "0001_initial"),
        (
            "wezeshaWebPortalCooperative",
            "0002_remove_cooperative_id_cooperative_cooperative_id",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmer",
            name="id",
        ),
        migrations.AddField(
            model_name="farmer",
            name="cooperative",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_cooperative",
                to="wezeshaWebPortalCooperative.cooperative",
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="farmer_id",
            field=models.SmallIntegerField(
                default=1, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="farmer",
            name="farmer_password",
            field=models.CharField(default="defaultpassword", max_length=20),
        ),
    ]
