# Generated by Django 5.0.6 on 2024-07-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "wezeshaMobileApp",
            "0002_remove_farmer_id_farmer_cooperative_farmer_farmer_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmer",
            old_name="cooperative",
            new_name="cooperative_id",
        ),
    ]
